# Generated by Django 5.1.2 on 2025-02-15 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_created', 'User Created')], max_length=50)),
                ('event_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retries', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='EventStore',
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['processed_at'], name='unprocessed_events_idx'),
        ),
    ]
