# Generated by Django 5.1.2 on 2025-02-15 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventlog", "0002_outboxevent_delete_eventstore_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outboxevent",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="outboxevent",
            name="unprocessed_events_idx",
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="last_error",
            field=models.TextField(blank=True, help_text="Описание последней ошибки", null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="max_retries",
            field=models.IntegerField(default=3, help_text="Максимальное количество попыток"),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="metadata_version",
            field=models.PositiveIntegerField(default=1, help_text="Версия структуры метаданных"),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, help_text="Время следующей попытки обработки", null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает обработки"),
                    ("processing", "В процессе обработки"),
                    ("failed", "Ошибка обработки"),
                    ("completed", "Обработано успешно"),
                ],
                default="pending",
                help_text="Текущий статус обработки события",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Время создания события"),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="event_data",
            field=models.JSONField(help_text="Данные события в формате JSON"),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="event_type",
            field=models.CharField(choices=[("user_created", "User Created")], help_text="Тип события", max_length=50),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="processed_at",
            field=models.DateTimeField(blank=True, help_text="Время успешной обработки события", null=True),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="retries",
            field=models.IntegerField(default=0, help_text="Количество попыток обработки"),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["status", "next_retry_at"], name="status_retry_idx"),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["created_at"], name="created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["event_type"], name="event_type_idx"),
        ),
    ]
